Project_Cus/urls.py
from django.urls import path

from Project_Cus import views

urlpatterns = [
    path('', views.homepage, name='cus_home'),
    path('home', views.homepage, name='cus_home'),
    path('login', views.login, name='cus_login'),
    path('logout', views.logout, name='cus_logout'),
    path('register', views.register, name='cus_register'),
    path('repair/form', views.repair_form, name='cus_repair_form'),
    path('repair/list', views.repair_list, name='cus_repair_list'),
    path('checkout/<order_id>', views.check_out, name='checkout'),
    path('pay/<order_rec_id>', views.check_out_qrcode, name='check_out_qrcode'),
    path('successcheckout/<order_rec_id>', views.check_out_success, name='check_out_success'),
]

Python_Project/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Project_Cus.urls')),
    path('cus/', include('Project_Cus.urls')),
    path('emp/', include('Project_UserEmp.urls')),
]

Project_UserEmp/models.py
from django.db import models
from django.db.models import ProtectedError
from Project_Cus.models import customer

class appointment(models.Model):
    app_id = models.CharField(max_length=10,primary_key=True)
    app_name = models.CharField(max_length=100,unique=True)
    app_permission = models.CharField(max_length=10,null=False,default="1")
    app_status = models.BooleanField(null=False,default='True')
    def __str__(self):
        return  self.app_name
class department(models.Model):
    dep_id = models.CharField(max_length=10,primary_key=True)
    dep_name_th = models.CharField(max_length=100,unique=True)
    dep_name_en = models.CharField(max_length=100, unique=True)
    dep_status = models.BooleanField(null=False,default='True')
    def __str__(self):
        return  self.dep_name_th
class tooltype(models.Model):
    tooly_id = models.CharField(max_length=10,primary_key=True)
    tooly_name = models.CharField(max_length=100,unique=True)
    tooly_status = models.BooleanField(null=False,default='True')
    tooly_des = models.TextField(null=True,blank=True,default="")
    def __str__(self):
        return self.tooly_name
class tool(models.Model):
    tool_id = models.CharField(max_length=10,primary_key=True)
    tool_name = models.CharField(max_length=100,unique=True)
    tool_price = models.FloatField(default=0.00,null=False)
    tool_type = models.ForeignKey(tooltype,on_delete=models.PROTECT,default=None)
    tool_des = models.TextField(null=True, blank=True, default="")
    tool_img = models.ImageField(upload_to="static/images/tool/",default="")

class employee(models.Model):
    id = models.CharField(max_length=10,primary_key=True)
    id_code = models.CharField(max_length=13,unique=True)
    first_name = models.CharField(max_length=255,null=False)
    sur_name = models.CharField(max_length=255,null=False)
    birthday = models.DateField(null=False)
    gender = models.CharField(max_length=20,null=False)
    national = models.CharField(max_length=100,null=False)
    ethnicity = models.CharField(max_length=100,null=False)
    religion = models.CharField(max_length=100,null=False)
    address = models.TextField(null=True,default='')
    subdistrict = models.CharField(max_length=100,null=False)
    district = models.CharField(max_length=100,null=False)
    Province = models.CharField(max_length=100,null=False)
    postcode = models.CharField(max_length=20,null=False)
    tel = models.CharField(max_length=10,null=False)
    email = models.CharField(max_length=100,null=False)
    appointment = models.ForeignKey(appointment,on_delete=models.PROTECT,default=None)
    department = models.ForeignKey(department,on_delete=models.PROTECT,default=None)
    username = models.CharField(max_length = 100,null=False)
    password = models.CharField(max_length=32,null=False)
    img_profile = models.ImageField(upload_to="static/images/employee/",blank=True, null=True,default="")

class order(models.Model):
    order_id = models.CharField(max_length=10,primary_key=True)
    title = models.CharField(max_length=255,null=False)
    desc = models.TextField(null=False,default='')
    tel_order = models.CharField(max_length=10,null=False)
    cus = models.ForeignKey(customer,on_delete=models.PROTECT,default=None)
    order_img = models.ImageField(upload_to="static/images/orders/",null=False,default="")
    order_status = models.IntegerField(null=False,default=0)
    create_date_time = models.CharField(null=False,max_length=50)
    submit_date_time = models.CharField(null=True,default="",blank=True,max_length=50)
    submit_emp = models.ForeignKey(employee,on_delete=models.PROTECT,default=None,null=True,blank=True)
class order_receive(models.Model):
    order_rec_id = models.CharField(max_length=10,primary_key=True)
    order = models.ForeignKey(order,on_delete=models.PROTECT,null=False)
    emp = models.ForeignKey(employee,on_delete=models.PROTECT,null=False)
    price = models.FloatField(default=0.00,null=True,blank=True)
    price_service = models.FloatField(default=0.00, null=True, blank=True)
    price_total = models.FloatField(default=0.00, null=True, blank=True)
    order_rec_date = models.CharField(null=False,max_length=50)
    order_rec_status = models.CharField(max_length=1,default="1")

class order_queue(models.Model):
    order_que_id = models.CharField(max_length=10,primary_key=True)
    order_receive = models.ForeignKey(order_receive,on_delete=models.PROTECT,null=False)
    order_que_number = models.IntegerField(default=1,null=False)
    order_que_date = models.CharField(null=False,max_length=50)
    order_que_status = models.CharField(max_length=1,default="1")
class repair_detail(models.Model):
    re_id = models.CharField(max_length=10, primary_key=True)
    order_receive = models.ForeignKey(order_receive, on_delete=models.PROTECT, null=False,unique=True)
    emp = models.ForeignKey(employee, on_delete=models.PROTECT, null=False)
    re_detail = models.TextField(null=False)
    re_date_start = models.CharField(null=True, default="", blank=True, max_length=50)
    re_date_end = models.CharField(null=True, default="", blank=True, max_length=50)

class tool_use(models.Model):
    tu_id = models.CharField(max_length=10, primary_key=True)
    tool = models.ForeignKey(tool, on_delete=models.PROTECT, null=False)
    order_receive = models.ForeignKey(order_receive, on_delete=models.PROTECT, null=False)
    tu_total_price = models.FloatField(default=0.00,null=False)
    tu_amount = models.IntegerField(default=1,null=False)
    tu_get_date = models.CharField(null=False,max_length=50)
class setting_default(models.Model):
    set_id = models.CharField(max_length=10, primary_key=True)
    service_paid = models.FloatField(default=200.00,null=False)
    line_notify = models.CharField(null=True,blank=True,max_length=100,default="")
class order_payment(models.Model):
    pay_id = models.CharField(max_length=10,primary_key=True)
    order_rec = models.ForeignKey(order_receive,on_delete=models.PROTECT,null=False,unique=True)
    pay_type = models.CharField(null=False,max_length=1)
    pay_img = models.ImageField(upload_to="static/images/pay/",null=True,blank=True,default="")
    pay_status = models.CharField(null=False,max_length=1)
    pay_date_send = models.CharField(null=True,max_length=50,blank=True,default="")
    pay_date_check = models.CharField(null=True,max_length=50,blank=True,default="")

templates/cus/checkout.html
{% include 'master/cus/base.html' %}
{% load static %}
{% block content %}
    <div class="main-wrapper cart-drawer-push">
        {% include 'master/cus/header.html' %}
        <main class="main-content">
            <div class="checkout-content my-5">
                <div class="container mt-5" style="padding-bottom: 200px">
                <div class="row">
                        <div class="col-md-12 text-center">
                            <h1>การชำระเงิน</h1>
                        </div>
                    </div>
                    <form action="{% url 'checkout' order_rec.order_id %}" id="form"
                          class="shiping-form needs-validation" novalidate method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="checkout-form col-12 col-sm-12 col-lg-8 mb-5 mb-lg-0 sidebar-left">
                                <div class="card rounded-0">
                                    <div class="card-header rounded-0">ที่อยู่ที่จัดส่ง</div>
                                    <div class="card-body">
                                        <div class="row form-group mb-0">
                                            <div class="col-12 col-sm-6 col-md-6 mb-4">
                                                <label>ชื่อ: *</label>
                                                {{ form.first_name }}
                                                <div class="invalid-feedback">Please enter your first name.</div>
                                            </div>
                                            <div class="col-12 col-sm-6 col-md-6 mb-4">
                                                <label>นามสกุล: *</label>
                                                {{ form.sur_name }}
                                                <div class="invalid-feedback">Please enter your last name.</div>
                                            </div>
                                        </div>
                                        <div class="row form-group mb-0">
                                            <div class="col-12 col-sm-12 col-md-12 mb-4">
                                                <label>ที่อยู่: *</label>
                                                {{ form.address }}
                                                <div class="invalid-feedback">Please enter your address.</div>
                                            </div>
                                        </div>
                                        <div class="row form-group mb-0">
                                            <div class="col-12 col-sm-6 col-md-6 mb-4">
                                                <label>ตำบล/เขต: *</label>
                                                {{ form.subdistrict }}
                                                <div class="invalid-feedback">Please select your country.</div>
                                            </div>
                                            <div class="col-12 col-sm-6 col-md-6 mb-4">
                                                <label>อำเภอ: *</label>
                                                {{ form.district }}
                                                <div class="invalid-feedback">Please select your state.</div>
                                            </div>
                                        </div>
                                        <div class="row form-group mb-0">
                                            <div class="col-12 col-sm-6 col-md-6 mb-4">
                                                <label>จังหวัด: *</label>
                                                {{ form.province }}
                                            </div>
                                            <div class="col-12 col-sm-6 col-md-6 mb-4">
                                                <label>รหัสไปรษณีย์: *</label>
                                                {{ form.postcode }}
                                                <div class="invalid-feedback">Please enter your zip/postal code.</div>
                                            </div>
                                        </div>
                                        <div class="row form-group mb-0">
                                            <div class="col-12 col-sm-6 col-md-6 mb-4">
                                                <label>เบอร์โทรที่ติดต่อได้: *</label>
                                                {{ form.tel }}
                                                <div class="invalid-feedback">Please enter your phone number.</div>
                                            </div>
                                            <div class="col-12 col-sm-6 col-md-6 mb-4">
                                                <label>อีเมลล์: *</label>
                                                {{ form.email }}
                                                <div class="invalid-feedback">Please enter your email.</div>
                                            </div>
                                        </div>
                                        <div class="row form-group mb-0">
                                            <div class="col-12 col-sm-12 col-md-12">
                                                <label>หมายเหตุ:</label>
                                                {{ form.note }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Shipping Form -->
                            </div>
                            <div class="checkout-order col-12 col-sm-12 col-lg-4 sidebar sidebar-right">
                                <h3>รายการอะไหล่ที่เปลี่ยน</h3>
                                <div class="table-content table-responsive mb-4">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th class="text-center"><b>อะไหล่</b></th>
                                            <th class="text-left"></th>
                                            <th class="text-center"><b>ราคา</b></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for key_tool in tool_use_data %}
                                            <tr>
                                                <td class="pro-img text-center">
                                                    <img class="img-fluid blur-up lazyload"
                                                         src="{% static key_tool.tool.tool_img %}"

                                                         title="image" width="60"/>
                                                </td>
                                                <td class="pro-del text-left">
                                                    <p class="mb-1 pro-name">{{ key_tool.tool.tool_name }}</p>
                                                    <p class="mb-1">จำนวน: {{ key_tool.tu_amount }}</p>
                                                </td>
                                                <td class="pro-price text-center">{{ key_tool.tu_total_price }}</td>
                                            </tr>
                                        {% endfor %}
                                        <tr>
                                            <td class="text-left" colspan="2"><b>ราคาทั้งหมด:</b></td>
                                            <td class="text-center font-14"><strong>{{ order_rec.price }}</strong></td>
                                        </tr>
                                        <tr>
                                            <td class="text-left" colspan="2"><b>ค่าบริการ:</b></td>
                                            <td class="text-center">
                                                <strong>
                                                    {% if order_rec.price_service > 0.0 %}
                                                        {{ order_rec.price_service }}
                                                    {% else %}
                                                        -
                                                    {% endif %}
                                                </strong>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="text-left" colspan="2"><b>ราคาสุทธิ:</b></td>
                                            <td class="text-center font-14"><strong>{{ order_rec.price_total }}</strong></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="payment-method accordion" id="payment-method">
                                    <div class="card border-0 rounded-0 mb-3">
                                        <div class="card-header border-0 rounded-0 p-0 bg-white">
                                            <div class="form-check" role="tablist" data-toggle="collapse"
                                                 data-target="#paymentOne" aria-expanded="true"
                                                 aria-controls="paymentOne">
                                                <input class="form-check-input" type="radio" name="pay_type"
                                                       id="pay_type1" value="1" checked/>
                                                <label class="form-check-label w-100 ml-3" for="pay_type1">เก็บเงินปลายทาง</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card border-0 rounded-0 mb-3">
                                        <div class="card-header border-0 rounded-0 bg-white p-0">
                                            <div class="form-check" role="tablist" data-toggle="collapse"
                                                 data-target="#paymentOne2" aria-expanded="false"
                                                 aria-controls="paymentOne2">
                                                <input class="form-check-input" type="radio" name="pay_type"
                                                       id="pay_type2" value="2"/>
                                                <label class="form-check-label w-100 ml-3" for="pay_type2">QR Code
                                                    Scan</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-5">
                                    <button type="submit"
                                            class="btn btn-primary btn-lg btn-block place-order-btn">ชำระเงิน
                                    </button>
                                </div>
                            </div>
                            <!-- End Cart Order -->
                        </div>
                    </form>
                </div>
            </div>
            <!-- End checkout -->
        </main>
        <div id="scrollTop"><i class="ti-arrow-up"></i></div>
        <div class="overlay"></div>
    </div>
    {% include 'master/cus/javaScipt.html' %}
    <script>

    </script>
{% endblock %}

templates/cus/checkout_success.html
{% include 'master/cus/base.html' %}
{% load static %}
{% block content %}
    <div class="main-wrapper cart-drawer-push">
        {% include 'master/cus/header.html' %}
        <main class="main-content">
                <!-- Start Checkout Success -->
                <div class="checkout-success-content">
                    <div class="container">
                        <div class="row row-sp">
                            <div class="col-sp col-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="card border-0 rounded-0">
                                    <div class="card-body text-center">
                                        <p class="checkout-success-icon"><i class="fa fa-check-square-o"></i></p>
                                        <h4 class="card-title">ขอบคุณสำหรับการชำระเงิน!</h4>
                                        <p class="card-text mb-1">Your order # is: <b>{{ order_rec.order.order_id }}</b>.</p>
                                        <p class="card-text mb-1">สินค้าจะจัดส่งให้แก่คุณ ตามที่อยู่ที่กรอกไปเมื่อสักครู่.</p>
                                        <p class="card-text mb-1">หลังจากตรวจสอบยอดโอน</p>
                                        <a href="{% url 'cus_repair_list' %}" class="btn btn-primary mt-4">ยืนยัน</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Checkout Success -->
            </main>
        <div id="scrollTop"><i class="ti-arrow-up"></i></div>
        <div class="overlay"></div>
    </div>
    {% include 'master/cus/javaScipt.html' %}
    <script>

    </script>
{% endblock %}

templates/cus/home.html
{% include 'master/cus/base.html' %}
{% load static %}

{% block content %}
    <div class="main-wrapper cart-drawer-push">
        {% include 'master/cus/header.html' %}
        <main class="main-content">

            <div class="ymm-slideshow position-relative sections-spacing">
                <div class="slideshow slideshow-banner">
                    <div class="single-slide slider-height bg-style d-flex align-items-center"
                         style="background-image:url({% static 'images/1.png' %});">

                    </div>
                    <div class="single-slide slider-height bg-style d-flex align-items-center"
                         style="background-image:url({% static 'images/2.png' %});">

                    </div>
                    <div class="single-slide slider-height bg-style d-flex align-items-center"
                         style="background-image:url({% static 'images/3.png' %});">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="title-btn clearfix">
                    <div class="section-header">
                        <h2>รายการซ่อมเสร็จ</h2>
                    </div>
                </div>
            </div>
            <div class="home-collection  sections-spacing">
                <div class="container-fluid p-0">
                    <div class="row no-gutters home-collection-prcarousel">
                        {% for key in order_data_success %}
                            <div class="col collection-item">
                                <div class="animate-scale collection-img">
                                    <img class="img-fluid blur-up lazyload " src="{% static key.order_img %}"
                                         style="width:381px; height:286px"/>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="popular-product sections-spacing">
                <div class="container">
                    <div class="title-btn clearfix">
                        <div class="section-header">
                            <h2>รายการแจ้งชำรุดล่าสุด</h2>

                        </div>
                    </div>
                    <div class="row row-sp row-eq-height">
                        {% for key in order_data_news %}
                            <div class="col-sp col-xl-3 col-lg-3 col-md-4 col-sm-6 col-6">
                                <div class="product-item">
                                    <div class="product-image-action">
                                        <div class="product-image">
                                            <div>
                                                <img class="img-fluid blur-up lazyload" src="{% static key.order_img %}"
                                                     style="width:381px; height:286px"/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}


                    </div>
                </div>
            </div>
        </main>


        {% include 'master/cus/footer.html' %}
        <div id="scrollTop"><i class="ti-arrow-up"></i></div>
        <div class="overlay"></div>
    </div>
    {% include 'master/cus/javaScipt.html' %}
{% endblock %}

templates/cus/repairList.html
{% include 'master/cus/base.html' %}
{% load static %}
{% load humanize %}
{% load bootstrap4 %}
{% block content %}
    <div class="main-wrapper cart-drawer-push">
        {% include 'master/cus/header.html' %}
        <main class="main-content">
            <div class="colection-listing mt-5">
                <div class="container ">
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <h1>รายการแจ้งชำรุด</h1>
                        </div>
                    </div>
                    <div class="row row-sp">
                        <div class="col-md-12">
                            <table class="table table-bordered ">
                                <thead style="background: #f76d2b">
                                <tr>
                                    <th>ลำดับ</th>
                                    <th>เลขคำสั่ง</th>
                                    <th>หัวข้อ</th>
                                    <th>ราคา</th>
                                    <th>รายละเอียดปัญหา</th>
                                    <th>วันที่แจ้ง</th>
                                    <th>สถานะ</th>
                                    <th>การชำระเงิน</th>
                                </tr>
                                </thead>
                                <tbody class="bg-white">
                                {% for key in order_data %}

                                    <tr>
                                        <td>{{ forloop.counter|add:order_data.start_index|add:"-1" }}</td>
                                        <td>{{ key.order_id }}</td>
                                        <td>{{ key.title }}</td>
                                        <td>{{ key.order_receive_set.values_list.0.5|intcomma }}</td>
                                        <td>{{ key.desc }}</td>
                                        <td>{{ key.create_date_time }}</td>
                                        <td class="block">
                                            <div class="collection-details">
                                                {% if key.order_status == 0 %}
                                                    <p class="text-info">
                                                        <i class="fas fa-sharp fa-solid fa-circle-exclamation mx-2"></i>รอรับงาน
                                                    </p>
                                                {% elif key.order_status == 1 %}
                                                    <p class="text-success">
                                                        <i class="fas fa-regular fa-screwdriver-wrench mx-2"></i>กำลังดำเนินการซ่อม
                                                    </p>
                                                {% elif key.order_status == 2 %}
                                                    <p class="text-success">
                                                        <i class="fas fa-sharp fa-solid fa-circle-exclamation mx-2"></i>รอชำระเงิน
                                                    </p>
                                                {% elif key.order_status == 3 %}
                                                    <p class="text-success"><i
                                                            class="fas fa-sharp fa-solid fa-circle-exclamation mx-2"></i>รอตรวจสอบชำระเงิน
                                                    </p>
                                                {% elif key.order_status == 4 %}
                                                    <p class="text-warning"><i class="fas fa-solid fa-truck mx-2"></i>กำลังจัดส่ง
                                                    </p>
                                                {% elif key.order_status == 5 %}
                                                    <p class="text-danger"><i class="fas fa-times mx-2"></i>รายการถูกยกเลิก
                                                    </p>
                                                {% endif %}
                                            </div>
                                        </td>
                                        <td>
                                            {% if key.order_status == 2 %}
                                                <a href="{% url 'checkout' key.order_id %}"
                                                   class="btn btn-primary">ชำระเงิน</a>
                                            {% endif %}
                                        </td>

                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            {% bootstrap_pagination order_data %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Collection List -->
        </main>
    </div>
    {% include 'master/cus/javaScipt.html' %}
{% endblock %}